//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advanced_Dynotis_Software.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advanced_Dynotis_Software.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About Us benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AboutPage_AboutUs {
            get {
                return ResourceManager.GetString("AboutPage_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At the heart of our endeavors lies the vision to be ranked among the top 25 Urban Air Mobility companies worldwide. With Semai, we are paving the way towards safer and cleaner urban air travel. Our mission extends to harnessing Turkey&apos;s high potential human resources, adding value and fostering employment within this burgeoning sector. Built for its unparalleled accuracy, our product enables customers to depend on the precision of the data they gather. This meticulous precision stems from our steadfast comm [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AboutPage_AboutUsText {
            get {
                return ResourceManager.GetString("AboutPage_AboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Value benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlertsPage_CurrentValue {
            get {
                return ResourceManager.GetString("AlertsPage_CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cutoff Max benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlertsPage_CutoffMax {
            get {
                return ResourceManager.GetString("AlertsPage_CutoffMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cutoff Min benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlertsPage_CutoffMin {
            get {
                return ResourceManager.GetString("AlertsPage_CutoffMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlertsPage_Device {
            get {
                return ResourceManager.GetString("AlertsPage_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlertsPage_Sensor {
            get {
                return ResourceManager.GetString("AlertsPage_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Limits benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlertsPage_SystemLimits {
            get {
                return ResourceManager.GetString("AlertsPage_SystemLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alerts benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlertsPage_Text {
            get {
                return ResourceManager.GetString("AlertsPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string APIPage_Text {
            get {
                return ResourceManager.GetString("APIPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automate Test benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AutomateTestPage {
            get {
                return ResourceManager.GetString("AutomateTestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Point benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AutomateTestPage_AddPoint {
            get {
                return ResourceManager.GetString("AutomateTestPage_AddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear All Points benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AutomateTestPage_ClearAllPoints {
            get {
                return ResourceManager.GetString("AutomateTestPage_ClearAllPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESC throttle output value(%) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AutomateTestPage_ESCOutput {
            get {
                return ResourceManager.GetString("AutomateTestPage_ESCOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AutomateTestPage_Index {
            get {
                return ResourceManager.GetString("AutomateTestPage_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AutomateTestPage_Save {
            get {
                return ResourceManager.GetString("AutomateTestPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AutomateTestPage_TestID {
            get {
                return ResourceManager.GetString("AutomateTestPage_TestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time (s) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AutomateTestPage_Time {
            get {
                return ResourceManager.GetString("AutomateTestPage_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Balancer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BalancerPage_Text {
            get {
                return ResourceManager.GetString("BalancerPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery (S) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BatterySecurityLimits_Battery {
            get {
                return ResourceManager.GetString("BatterySecurityLimits_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the battery level benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BatterySecurityLimits_BatteryToolTip {
            get {
                return ResourceManager.GetString("BatterySecurityLimits_BatteryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. Current (A) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BatterySecurityLimits_MaxCurrent {
            get {
                return ResourceManager.GetString("BatterySecurityLimits_MaxCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the safe current limit for the system benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BatterySecurityLimits_MaxCurrenToolTip {
            get {
                return ResourceManager.GetString("BatterySecurityLimits_MaxCurrenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. Device benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CoaxialTestPage_1Device {
            get {
                return ResourceManager.GetString("CoaxialTestPage_1Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2. Device benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CoaxialTestPage_2Device {
            get {
                return ResourceManager.GetString("CoaxialTestPage_2Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CoaxialTestPage_Open {
            get {
                return ResourceManager.GetString("CoaxialTestPage_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coaxial Test benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CoaxialTestPage_Text {
            get {
                return ResourceManager.GetString("CoaxialTestPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Air Density benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_AirDensity {
            get {
                return ResourceManager.GetString("DeviceCard_AirDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ambient Temp. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_AmbientTemp {
            get {
                return ResourceManager.GetString("DeviceCard_AmbientTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current (A) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_ChartCurrent {
            get {
                return ResourceManager.GetString("DeviceCard_ChartCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor Speed (RPM) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_ChartMotorSpeed {
            get {
                return ResourceManager.GetString("DeviceCard_ChartMotorSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thrust (gf) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_ChartThrust {
            get {
                return ResourceManager.GetString("DeviceCard_ChartThrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time (s) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_ChartTime {
            get {
                return ResourceManager.GetString("DeviceCard_ChartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torque (Nmm) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_ChartTorque {
            get {
                return ResourceManager.GetString("DeviceCard_ChartTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vibration (g) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_ChartVibration {
            get {
                return ResourceManager.GetString("DeviceCard_ChartVibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage (V) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_ChartVoltage {
            get {
                return ResourceManager.GetString("DeviceCard_ChartVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_Current {
            get {
                return ResourceManager.GetString("DeviceCard_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor Speed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_MotorSpeed {
            get {
                return ResourceManager.GetString("DeviceCard_MotorSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor Temp. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_MotorTemp {
            get {
                return ResourceManager.GetString("DeviceCard_MotorTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_Power {
            get {
                return ResourceManager.GetString("DeviceCard_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pressure benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_Pressure {
            get {
                return ResourceManager.GetString("DeviceCard_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thrust benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_Thrust {
            get {
                return ResourceManager.GetString("DeviceCard_Thrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torque benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_Torque {
            get {
                return ResourceManager.GetString("DeviceCard_Torque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vibration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_Vibration {
            get {
                return ResourceManager.GetString("DeviceCard_Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_Voltage {
            get {
                return ResourceManager.GetString("DeviceCard_Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wind Direction benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_WindDirection {
            get {
                return ResourceManager.GetString("DeviceCard_WindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wind Speed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceCard_WindSpeed {
            get {
                return ResourceManager.GetString("DeviceCard_WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery (S) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_Battery {
            get {
                return ResourceManager.GetString("DeviceInformation_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESC Status benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_ESCStatus {
            get {
                return ResourceManager.GetString("DeviceInformation_ESCStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESC Value (%) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_ESCValue {
            get {
                return ResourceManager.GetString("DeviceInformation_ESCValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firmware benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_Firmware {
            get {
                return ResourceManager.GetString("DeviceInformation_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal Res. (mΩ) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_InternalRes {
            get {
                return ResourceManager.GetString("DeviceInformation_InternalRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Current (A) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_MaxCurrent {
            get {
                return ResourceManager.GetString("DeviceInformation_MaxCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_Mode {
            get {
                return ResourceManager.GetString("DeviceInformation_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_Model {
            get {
                return ResourceManager.GetString("DeviceInformation_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Load Current (A) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_NoLoadCurrent {
            get {
                return ResourceManager.GetString("DeviceInformation_NoLoadCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_PortName {
            get {
                return ResourceManager.GetString("DeviceInformation_PortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Propeller Diameter (Inch) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_PropellerDiameter {
            get {
                return ResourceManager.GetString("DeviceInformation_PropellerDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save File benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_SaveFile {
            get {
                return ResourceManager.GetString("DeviceInformation_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Status benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_SaveStatus {
            get {
                return ResourceManager.GetString("DeviceInformation_SaveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Security Status benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_SecurityStatus {
            get {
                return ResourceManager.GetString("DeviceInformation_SecurityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seri No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_SeriNo {
            get {
                return ResourceManager.GetString("DeviceInformation_SeriNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_TestMode {
            get {
                return ResourceManager.GetString("DeviceInformation_TestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Informations benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceInformation_Text {
            get {
                return ResourceManager.GetString("DeviceInformation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Status: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceMiniCard_ConnectionStatus {
            get {
                return ResourceManager.GetString("DeviceMiniCard_ConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Informations benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceMiniCard_DeviceInformation {
            get {
                return ResourceManager.GetString("DeviceMiniCard_DeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceMiniCard_Error {
            get {
                return ResourceManager.GetString("DeviceMiniCard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firmware: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceMiniCard_Firmware {
            get {
                return ResourceManager.GetString("DeviceMiniCard_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceMiniCard_Model {
            get {
                return ResourceManager.GetString("DeviceMiniCard_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port Name: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceMiniCard_PortName {
            get {
                return ResourceManager.GetString("DeviceMiniCard_PortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seri No: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceMiniCard_SeriNo {
            get {
                return ResourceManager.GetString("DeviceMiniCard_SeriNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working Status: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeviceMiniCard_WorkingStatus {
            get {
                return ResourceManager.GetString("DeviceMiniCard_WorkingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor Efficiency benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EffVariables_MotorEfficiency {
            get {
                return ResourceManager.GetString("EffVariables_MotorEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Efficiency of the brushless motor used. Calculated based on the motor parameter inputs. Note that ESC efficiency is considered as constant as %95. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EffVariables_MotorEfficiencyTooltip {
            get {
                return ResourceManager.GetString("EffVariables_MotorEfficiencyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Propeller Efficiency benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EffVariables_PropellerEfficiency {
            get {
                return ResourceManager.GetString("EffVariables_PropellerEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Also known as Figure of Merit, this value gives you the static performance of your propeller. Motor and ESC is not included in the calculations. Propeller diameter, RPM, air density, torque and thrust values are used as input for this calculation. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EffVariables_PropellerEfficiencyTooltip {
            get {
                return ResourceManager.GetString("EffVariables_PropellerEfficiencyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Propulsion System Efficiency I benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EffVariables_PropulsionSystemEfficiencyI {
            get {
                return ResourceManager.GetString("EffVariables_PropulsionSystemEfficiencyI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Propulsion System Efficiency II benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EffVariables_PropulsionSystemEfficiencyII {
            get {
                return ResourceManager.GetString("EffVariables_PropulsionSystemEfficiencyII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Propulsion system efficiency in terms of grams per watt power. The higher is the better. Typical range is between 6 to 15. If it is below 6, then your propeller disc loading is high. Try using lower Kv motor and bigger diameter propeller. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EffVariables_PropulsionSystemEfficiencyIITooltip {
            get {
                return ResourceManager.GetString("EffVariables_PropulsionSystemEfficiencyIITooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is the overall efficiency of the propulsion system including motor, ESC and the propeller. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EffVariables_PropulsionSystemEfficiencyITooltip {
            get {
                return ResourceManager.GetString("EffVariables_PropulsionSystemEfficiencyITooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal Res. (mΩ) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentParameters_InternalRes {
            get {
                return ResourceManager.GetString("EquipmentParameters_InternalRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the motor internal resistance. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentParameters_InternalResToolTip {
            get {
                return ResourceManager.GetString("EquipmentParameters_InternalResToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Load Current (A) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentParameters_NoLoadCurrent {
            get {
                return ResourceManager.GetString("EquipmentParameters_NoLoadCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the motor I₀(A) current. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentParameters_NoLoadCurrentToolTip {
            get {
                return ResourceManager.GetString("EquipmentParameters_NoLoadCurrentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Propeller Diameter (Inch) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentParameters_PropellerDiameter {
            get {
                return ResourceManager.GetString("EquipmentParameters_PropellerDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the propeller diameter. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EquipmentParameters_PropellerDiameterToolTip {
            get {
                return ResourceManager.GetString("EquipmentParameters_PropellerDiameterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increase by 5 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ESC_Increaseby5 {
            get {
                return ResourceManager.GetString("ESC_Increaseby5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock/UnLock ESC benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ESC_LockUnLockESC {
            get {
                return ResourceManager.GetString("ESC_LockUnLockESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop ESC benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ESC_StopESC {
            get {
                return ResourceManager.GetString("ESC_StopESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESC Calibration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ESCCalibrationPage_Text {
            get {
                return ResourceManager.GetString("ESCCalibrationPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HelpPage_Text {
            get {
                return ResourceManager.GetString("HelpPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to Advanced Dynotis Software benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HomePage_Text {
            get {
                return ResourceManager.GetString("HomePage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LanguagePage_English {
            get {
                return ResourceManager.GetString("LanguagePage_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Languages benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LanguagePage_Languages {
            get {
                return ResourceManager.GetString("LanguagePage_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turkish benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LanguagePage_Turkish {
            get {
                return ResourceManager.GetString("LanguagePage_Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainWindow_API {
            get {
                return ResourceManager.GetString("MainWindow_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainWindow_Automate {
            get {
                return ResourceManager.GetString("MainWindow_Automate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coaxial Test benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainWindow_Coaxial {
            get {
                return ResourceManager.GetString("MainWindow_Coaxial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainWindow_Home {
            get {
                return ResourceManager.GetString("MainWindow_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi Test benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainWindow_Multi {
            get {
                return ResourceManager.GetString("MainWindow_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Script benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainWindow_Script {
            get {
                return ResourceManager.GetString("MainWindow_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single Test benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainWindow_Single {
            get {
                return ResourceManager.GetString("MainWindow_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Propeller Balancer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MultiTestPage_Balancer {
            get {
                return ResourceManager.GetString("MultiTestPage_Balancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi Test benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MultiTestPage_Text {
            get {
                return ResourceManager.GetString("MultiTestPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Record_FileName {
            get {
                return ResourceManager.GetString("Record_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter file name. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Record_FileNameToolTip {
            get {
                return ResourceManager.GetString("Record_FileNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Record_Recording {
            get {
                return ResourceManager.GetString("Record_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SaveConfigPage_Text {
            get {
                return ResourceManager.GetString("SaveConfigPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Script benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ScriptPage_Text {
            get {
                return ResourceManager.GetString("ScriptPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPage_About {
            get {
                return ResourceManager.GetString("SettingsPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alerts benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPage_Alerts {
            get {
                return ResourceManager.GetString("SettingsPage_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESC Calibration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPage_ESCCalibration {
            get {
                return ResourceManager.GetString("SettingsPage_ESCCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPage_Help {
            get {
                return ResourceManager.GetString("SettingsPage_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPage_Language {
            get {
                return ResourceManager.GetString("SettingsPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPage_RecordingSettings {
            get {
                return ResourceManager.GetString("SettingsPage_RecordingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updates benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPage_SoftwareUpdates {
            get {
                return ResourceManager.GetString("SettingsPage_SoftwareUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPage_Text {
            get {
                return ResourceManager.GetString("SettingsPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Units Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SettingsPage_UnitsSettings {
            get {
                return ResourceManager.GetString("SettingsPage_UnitsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SingleTestPage_Open {
            get {
                return ResourceManager.GetString("SingleTestPage_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single Test benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SingleTestPage_Text {
            get {
                return ResourceManager.GetString("SingleTestPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firmware  Updates benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SoftwareUpdatePage_FirmwareText {
            get {
                return ResourceManager.GetString("SoftwareUpdatePage_FirmwareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Software Updates benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SoftwareUpdatePage_Text {
            get {
                return ResourceManager.GetString("SoftwareUpdatePage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tare benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tare_Tare {
            get {
                return ResourceManager.GetString("Tare_Tare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor Speed: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnitsSettingsPage_MotorSpeed {
            get {
                return ResourceManager.GetString("UnitsSettingsPage_MotorSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pressure: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnitsSettingsPage_Pressure {
            get {
                return ResourceManager.GetString("UnitsSettingsPage_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnitsSettingsPage_Temperature {
            get {
                return ResourceManager.GetString("UnitsSettingsPage_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Units Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnitsSettingsPage_Text {
            get {
                return ResourceManager.GetString("UnitsSettingsPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thrust: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnitsSettingsPage_Thrust {
            get {
                return ResourceManager.GetString("UnitsSettingsPage_Thrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torque: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnitsSettingsPage_Torque {
            get {
                return ResourceManager.GetString("UnitsSettingsPage_Torque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wind Speed: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnitsSettingsPage_WindSpeed {
            get {
                return ResourceManager.GetString("UnitsSettingsPage_WindSpeed", resourceCulture);
            }
        }
    }
}
