//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advanced_Dynotis_Software.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advanced_Dynotis_Software.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Air Density benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AirDensity {
            get {
                return ResourceManager.GetString("AirDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ambient Temp benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AmbientTemp {
            get {
                return ResourceManager.GetString("AmbientTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current (A) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChartCurrent {
            get {
                return ResourceManager.GetString("ChartCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor Speed (RPM) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChartMotorSpeed {
            get {
                return ResourceManager.GetString("ChartMotorSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thrust (gf) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChartThrust {
            get {
                return ResourceManager.GetString("ChartThrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torque (Nmm) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChartTorque {
            get {
                return ResourceManager.GetString("ChartTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vibration (g) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChartVibration {
            get {
                return ResourceManager.GetString("ChartVibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage (V) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChartVoltage {
            get {
                return ResourceManager.GetString("ChartVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Languages benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor Speed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MotorSpeed {
            get {
                return ResourceManager.GetString("MotorSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Motor Temp benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MotorTemp {
            get {
                return ResourceManager.GetString("MotorTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pressure benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thrust benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Thrust {
            get {
                return ResourceManager.GetString("Thrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Torque benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Torque {
            get {
                return ResourceManager.GetString("Torque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turkish benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vibration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Vibration {
            get {
                return ResourceManager.GetString("Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wind Direction benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WindDirection {
            get {
                return ResourceManager.GetString("WindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wind Speed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
    }
}
